#%RAML 1.0 Library
usage: |
  Basic Types used in the Agent Client authorisation invitations API
uses:
  atoms: atoms.raml
types:

  LinkSection: atoms.LinkSection
  Regime:      atoms.Regime
  Status:      atoms.Status
  Timestamp:   atoms.Timestamp

  Invitation:
    displayName: Invitation
    description: |
        Invitations provide clients with the facility to confer permission to an
        agent to act on their behalf when dealing with HMRC
    type: object
    properties:
      _links: LinkSection
      created: Timestamp
      lastUpdated: Timestamp
      arn:
        description: The Agent Registration Number
        type: string
      regime:
        description: The tax regime specified in the invitation
        type: Regime
      clientId:
        description: Client's top level ID for their MTD registration (not regime specific)
        type: string
      postcode:
        description: The client's postcode.
        type: string
      status:
        type: Status
  example: !include ../examples/get-agency-invitation-example.json

  Invitations:
    description: Invitations is the collection of invitations that either an agent or client has sent or recieved
    properties:
      _links: LinkSection
      _embedded:
        properties:
          invitations: Invitation[]
    example: !include invitations_example.json
