#%RAML 1.0
title: Invitations API
baseUri: https://gov.uk/agent-client-authorisation/
version: v1
mediaType: application/json
types:
  Status:
    description: |
      The statuses that an Invitation can have

        Status  | Meaning
        ------- | -------
        ```pending``` | The invitation has been created, it has not been accepted or rejected by the Customer. Only the service can set this status
        ```accepted``` | The Customer has accepted the invitation. Only the Customer can set this status
        ```rejected``` | The Customer has rejected the invitation. Only the Customer can set this status
        ```cancelled``` | The Agency has cancelled the invitation. Only the Agency can set this status
    type: string
    enum: [ pending, accepted, rejected, cancelled ]
  Invitation:
    type: object
    description: |
         An invitation represents a request from an Agency to a Customer to permit the Agency to act on the
         Customer's behalf when dealing wtih HMRC
    properties:
      created: 
        type: datetime
        format: rfc2616
      lastUpdated:
        type: datetime
        format: rfc2616
      regime:
        description: The tax regime for which authorisation is being requested. N.B. this list will expand.
        type: string
        enum: [ sa ]
      customerRegimeId:
        description: The identifier of the Customer within the regime, e.g. UTR for SA.
        type: string
      agencyName:
        description: Name of the Agency requesting authorisation.
        type: string
      agentName:
        description: Name of the Agent requesting authorisation.
        type: string
      status:
        type: Status
    example:
      accepted:
          created: "2016-06-27T01:55:28+00.00",
          lastUpdated: "2016-07-02T01:55:28+00.00",
          regime: "sa",
          agencyName: "Sally Hughes Accountants",
          agentName: "Bob McCratchet",
          customerRegimeId: "123456789",
          status: "accepted"

/agencies/{mtdArn}/invitations/sent:
    get:
      description: Get the list of invitations for this agency.
      queryParameters:
        status:
          description: filter invitations by status.
          type: Status
        customerRegimeId:
          type: string
        regime:
          type: string
          enum: [ sa ]
      responses:
        200:
          description: A list of invitations.
          body: Invitation[]
        204:
          description: No invitations matched the search criteria.
        401:
          description: The caller must be authenticated and authorised (logged-in) to use this resource
    post:
      description: Create a new invitation.
      body:
        type: Invitation
        example: 
          newInvitation: |
            {
              "regime" : "sa",
              "customerRegimeId" : "123456789"
            }
      responses:
        201:
          description: The invitation was successfully created.
          headers:
            Location:
              example: /agencies/A123456/invitations/sent/INV123456
        401:
          description: The caller must be authenticated and authorised (logged-in) to use this resource
        403:
          description: |
            The request will not be fulfilled. Reasons for this may include
               * The agency does not have the requisite active enrolments
               * The customer is not registered for that tax regime
      uriParameters:
        mtdArn:
          description: The MTD platform Agent Reference Number
          type: string
    /{invitationId}:
      delete:
        description: Cancel an invitation.
        responses:
          204:
            description: Invitation has been cancelled.
          401:
            description: The caller must be authenticated and authorised (logged-in) to use this resource
          404:
            description: The invitation with the specified id does not exist.
      get:
        description: Retrieve an invitation.
        responses:
          200:
            description: Returns the invitation.
            body:
              type: Invitation
              example:
                pending: |
                  {
                    "_links": {
                      "self": {"href": "/url/of/this/invitation"},
                      "cancel": {"href": "/url/to/cancel/this/invitation"}
                    },
                    "created": "2016-06-27T01:55:28+00.00",
                    "lastUpdated": "2016-07-02T01:55:28+00.00",
                    "regime" : "sa",
                    "agencyName" : "Sally Hughes Accountants",
                    "agentName" : "Bob McCratchet",
                    "customerRegimeId" : "123456789",
                    "status": "pending"
                  }
          401:
            description: The caller must be authenticated and authorised (logged-in) to use this resource
          404:
            description: The invitation with the specified id does not exist.
      uriParameters:
        invitationId:
          description: The id of the invitation.
          type: string

/customers/{id}/invitations/received:
    get:
      queryParameters:
        status:
          description: filter invitations by status.
          type: Status
      responses:
        200:
          description: A list of invitations.
          body: Invitation[]
        204:
          description: No invitations matched the search criteria.
        401:
          description: The caller must be authenticated and authorised (logged-in) to use this resource
    uriParameters:
      id:
        description: Customer identifier.
        type: string
    /{invitationId}:
      get:
        description: Retrieve an invitation.
        responses:
          200:
            description: Returns the invitation.
            body:
              type: Invitation
              example:
                pending: |
                  {
                    "_links": {
                      "self": {"href": "/url/of/this/invitation"},
                      "accept": {"href": "/url/to/accept/this/invitation"},
                      "reject": {"href": "/url/to/reject/this/invitation"}
                    },
                    "created": "2016-06-27T01:55:28+00.00",
                    "lastUpdated": "2016-07-02T01:55:28+00.00",
                    "regime" : "sa",
                    "agencyName" : "Sally Hughes Accountants",
                    "agentName" : "Bob McCratchet",
                    "customerRegimeId" : "123456789",
                    "status": "pending"
                  }
          401:
            description: The caller must be authenticated and authorised (logged-in) to use this resource
          404:
            description: The invitation with the specified id does not exist.
      uriParameters:
        invitationId:
          description: The id of the invitation.
          type: string
      /accept:
        description: Accept an invitation.
        put:
          responses:
            204:
              description: Invitation has been accepted.
            401:
              description: The caller must be authenticated and authorised (logged-in) to use this resource
            404:
              description: The invitation with the specified id does not exist.
      /reject:
        description: Accept an invitation.
        put:
          responses:
            204:
              description: Invitation has been rejected.
            401:
              description: The caller must be authenticated and authorised (logged-in) to use this resource
            404:
              description: The invitation with the specified id does not exist.
