#%RAML 1.0
title: Agent Client Authorisation
version: 0.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: [ application/json, application/hal+json ]
description: An API for agents and clients akin to the paper 64-8 form.  The production version of this API is not yet available, only the test version which should be accessed using your test credentials.

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include http://api-documentation-raml-frontend.service/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include http://api-documentation-raml-frontend.service/api-documentation/assets/common/docs/errors.md

uses:
  sec: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/securitySchemes.raml
  headers: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/headers.raml
  annotations: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/annotations.raml
  types: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/types.raml
  invitations: modules/invitations.raml
  atoms:       modules/atoms.raml

traits:
  loginRequired:
    responses:
      401:
        body:
          application/json:
            description: Invalid Authentication information provided
            type: !include schemas/error.json
            example:  !include examples/login-required-example.json

  permissionOnAgencyRequired:
    responses:
      403:
        body:
          application/json:
            description: The logged in user is not permitted to access invitations for the specified agency.
            type: !include schemas/error.json
            example:  !include examples/permission-on-agency-required-example.json

  permissionOnClientRequired:
    responses:
      403:
        body:
          application/json:
            description: The logged in user is not permitted to see the invitations for the specified client.
            type: !include schemas/error.json
            example:  !include examples/permission-on-client-required-example.json

  mustBeAnAgent:
    responses:
      403:
        body:
          application/json:
            description: The logged in user is not an agent.
            type: !include schemas/error.json
            example:  !include examples/must-be-an-agent-example.json

  mustBeASaClient:
    responses:
      403:
        body:
          application/json:
            description: The Client must have an active IR-SA enrolment.
            type: !include schemas/error.json
            example:  !include examples/must-be-a-sa-client-example.json

  agentRegistrationRequired:
    responses:
      403:
        body:
          application/json:
            description: The Agent's MTDfB registration was not found.
            type: !include schemas/error.json
            example:  !include examples/agent-registration-required-example.json

  clientRegistrationRequired:
    responses:
      403:
        body:
          application/json:
            description: The Client's MTDfB registration was not found.
            type: !include schemas/error.json
            example:  !include examples/client-registration-required-example.json

  invitationMustHaveValidStatus:
    responses:
      403:
        body:
          application/json:
            description: The requested state transition is not permitted given the invitation's current status.
            type: !include schemas/error.json
            example:  !include examples/invitation-must-have-valid-status-example.json

  invitationSpecified:
    responses:
      404:
        body:
          application/json:
            description: The specified invitation was not found.
            type: !include schemas/error.json
            example:  !include examples/invitation-not-found-example.json

/agent-client-authorisation/agencies/{arn}/invitations/sent:
  is: [headers.acceptHeader, loginRequired, mustBeAnAgent, agentRegistrationRequired, permissionOnAgencyRequired]
  uriParameters:
    arn:
      description: The MTD platform Agent Registration Number.
      type: string
  get:
    displayName: Get invitations sent by the agency
    description: Retrieves a list of invitations sent by the agency.
    (annotations.scope): "read:sent-invitations"
    securedBy: [ sec.oauth_2_0: { scopes: [ "read:sent-invitations" ] } ]
    queryParameters:
      status:
        type: invitations.Status
        description: Filter invitations by status. If multiple 'status' filtering parameters are supplied then only the first is considered.
        required: false
      clientId:
        type: string
        description: Client's top level ID for their MTD registration (not regime specific).
        required: false
      regime:
        type: invitations.Regime
        description: The tax regime.
        required: false
    responses:
      200:
        description: A list of invitations.
        #TODO status descriptions (see Agency-Sent-Invitations.xml) - can they be generated from JSON Schema?
        #TODO description of links (see Agency-Sent-Invitations.xml)
        body:
          application/json:
            examples:
              example-1:
                value: !include examples/get-agency-invitations-sent-example-1.json
  post:
    is: [clientRegistrationRequired]
    displayName: Create a new invitation
    #TODO replace request body HTML table in description with JSON schema
    description: |
      Create a new invitation.

      The request body should be a JSON object with the following properties:

      <table>
        <tr><th>Property</th><th>Example</th><th>Description</th></tr>
        <tr><td>regime</td><td>mtd-sa</td><td>The tax regime of the client within which the agency is offering representation.</td></tr>
        <tr><td>clientId</td><td>1234567890</td><td>Client's top level ID for their MTD registration (not regime specific).</td></tr>
        <tr><td>postcode (known fact)</td><td>XM4 5HQ</td><td>This varies between regimes. In this example, for mtd-sa, it is the registered postcode of the client.</td></tr>
      </table>
    (annotations.scope): "write:sent-invitations"
    securedBy: [ sec.oauth_2_0: { scopes: [ "write:sent-invitations" ] } ]
    body:
      application/json:
        type: atoms.AgentInvitation
        examples:
          example-1:
            value: !include examples/post-agency-invitations-sent-example-1.json
    responses:
      201:
        description: The invitation was successfully created.
        headers:
          Location:
            example: /agencies/A123456/invitations/sent/INV123456
            description: Location of the invitation that was created.
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              invalidPostcode:
                description: The submitted postcode does not match the expected format.
                value:
                  code: POSTCODE_FORMAT_INVALID
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              postcodeDoesNotMatch:
                description: The submitted postcode did not match the client's postcode as held by HMRC.
                value:
                  code: POSTCODE_DOES_NOT_MATCH
      501:
        body:
          application/json:
            type: types.errorResponse
            examples:
              postcodeDoesNotMatch:
                description: The submitted regime is not currently supported by this API.
                value:
                  code: UNSUPPORTED_REGIME

  /{invitationId}:
    is: [headers.acceptHeader, loginRequired, mustBeAnAgent, agentRegistrationRequired, permissionOnAgencyRequired, invitationSpecified]
    uriParameters:
      invitationId:
        description: The id of the invitation.
        type: string
    get:
      displayName: Get a sent invitation
      description: Retrieve a sent invitation.
      (annotations.scope): "read:sent-invitations"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:sent-invitations" ] } ]
      responses:
        200:
          description: Returns the invitation.
          body:
            application/json:
              #TODO: JSON Schema # type: invitations.Invitation
              example: !include modules/invitation_example.json
        401:
          description: The agent must be authenticated and authorised (logged-in) to use this resource
        403:
          description: The agent is not permitted to see this invitation.
        404:
          description: The invitation with the specified id does not exist.
    /cancel:
      is: [headers.acceptHeader, loginRequired, mustBeAnAgent, agentRegistrationRequired, permissionOnAgencyRequired, invitationSpecified, invitationMustHaveValidStatus]
      put:
        displayName: Cancel an invitation
        description: Cancel an invitation.
        (annotations.scope): "write:sent-invitations"
        securedBy: [ sec.oauth_2_0: { scopes: [ "write:sent-invitations" ] } ]
        responses:
          204:
            description: Invitation has been cancelled.
          401:
            description: The agent must be authenticated and authorised (logged-in) to use this resource
          403:
            description: The agent is not permitted to cancel this invitation, for example because it has already been accepted or rejected.
          404:
            description: The invitation with the specified id does not exist.

/agent-client-authorisation/clients/{clientId}/invitations/received:
  is: [headers.acceptHeader, loginRequired, mustBeASaClient, clientRegistrationRequired, permissionOnClientRequired]
  uriParameters:
    clientId:
      description: Client identifier.
      type: string
  get:
    displayName: Get invitations received by a client
    description: Retrieves a list of invitations received by a client
    (annotations.scope): "read:received-invitations"
    securedBy: [ sec.oauth_2_0: { scopes: [ "read:received-invitations" ] } ]
    queryParameters:
      status:
        description: filter invitations by status. If multiple 'status' filtering parameters are supplied then only the first is considered.
        type: atoms.Status
        required: false
    responses:
      200:
        description: A list of invitations.
        body: #invitations.Invitation[]
          application/json:
            example:
                value: !include examples/get-client-invitations-sent-example.json
      401:
        description: The client must be authenticated and authorised (logged-in) to use this resource
      403:
        description: The client is not permitted to see these invitations.

  /{invitationId}:
    is: [headers.acceptHeader, loginRequired, mustBeASaClient, clientRegistrationRequired, permissionOnClientRequired, invitationSpecified]
    get:
      displayName: Get a received invitation
      description: Retrieve a received invitation.
      (annotations.scope): "read:received-invitations"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:received-invitations" ] } ]
      responses:
        200:
          description: Returns the invitation.
          body:
            #type: invitations.Invitation
            application/json:
              example:
                  value: !include examples/get-client-invitations-sent-example.json
        401:
          description: The client must be authenticated and authorised (logged-in) to use this resource
        403:
          description: The client is not permitted to reject this invitation, for example because it has already been accepted, rejected or cancelled.
        404:
          description: The invitation with the specified id does not exist.
    uriParameters:
      invitationId:
        description: The id of the invitation.
        type: string
    /accept:
      is: [headers.acceptHeader, loginRequired, mustBeASaClient, clientRegistrationRequired, permissionOnClientRequired, invitationSpecified, invitationMustHaveValidStatus]
      put:
        displayName: Accept an invitation
        description: Accept an invitation.
        (annotations.scope): "write:received-invitations"
        securedBy: [ sec.oauth_2_0: { scopes: [ "write:received-invitations" ] } ]
        responses:
          204:
            description: Invitation has been accepted.
          401:
            description: The client must be authenticated and authorised (logged-in) to use this resource
          403:
            description: The client is not permitted to reject this invitation, for example because it has already been accepted, rejected or cancelled.
          404:
            description: The invitation with the specified id does not exist.
    /reject:
      is: [headers.acceptHeader, loginRequired, mustBeASaClient, clientRegistrationRequired, permissionOnClientRequired, invitationSpecified, invitationMustHaveValidStatus]
      put:
        displayName: Reject an invitation
        description: Reject an invitation.
        (annotations.scope): "write:received-invitations"
        securedBy: [ sec.oauth_2_0: { scopes: [ "write:received-invitations" ] } ]
        responses:
          204:
            description: Invitation has been rejected.
          401:
            description: The client must be authenticated and authorised (logged-in) to use this resource
          403:
            description: The client is not permitted to reject this invitation.
          404:
            description: The invitation with the specified id does not exist.
